version: "3.8"
services:
  mycarshop:
    depends_on:
      - mariadb
    image: "mycarshop"
    container_name: "mycarshop-service"
    ports:
      - 8080:8080
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/project2db

  mariadb:
    image: "mariadb"
    container_name: "mariadb"
    ports:
      - 3305:3306
    environment:
      - MARIADB_ROOT_PASSWORD=abcd1234
      - MARIADB_USER=webuser
      - MARIADB_DATABASE=project2db
      - MARIADB_PASSWORD=abcd1234
