version: "3.8"
services:
  mariadb:
    image: "mariadb"
    container_name: "mariadb"
    ports:
      - 3305:3306
    environment:
      - MARIADB_ROOT_PASSWORD=abcd1234
      - MARIADB_USER=webuser
      - MARIADB_DATABASE=project2db
      - MARIADB_PASSWORD=abcd1234
    networks:
      - mycarshop_nw1

  config-service:
    build:
      context: D:\project\Intellij_project\cloud-native\config-service
      dockerfile: Dockerfile
    container_name: "config-service"
    ports:
      - 8888:8888
    networks:
      - mycarshop_nw1
    expose:
      - 8888

  mycarshop:
    depends_on:
      - mariadb
      - config-service
    build:
      context: D:\project\Intellij_project\mycarshop
      dockerfile: Dockerfile
    container_name: "mycarshop-service"
    ports:
      - 8080:8080
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/project2db
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MariaDBDialect
    networks:
      - mycarshop_nw1
    restart: always

networks:
  mycarshop_nw1: